### ISSUE TITLE
Lab 1.1 - Diaz de Valdes

### ISSUE THREAD

**Issue by consueloddv** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-consueloddv#1]
<img width="997" alt="Captura de pantalla 2023-10-30 a la(s) 16 13 04" src="https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-consueloddv/assets/148822227/924f67d5-8a2f-438e-8596-a28f171071ac">

**Comment by instructorc** [comment]
Deliverable met
