### ISSUE TITLE
Lab 2.2

### ISSUE THREAD

**Issue by consueloddv** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-consueloddv#2]
<img width="1067" alt="Captura de pantalla 2023-11-02 a la(s) 13 50 35" src="https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-consueloddv/assets/148822227/ddf7b15b-0c95-492d-92bb-75d808a90b8f">

**Comment by instructorc** [comment]
Deliverable met!
